use_frameworks!

platform :ios, '9.0'

target 'RRCountryCodePicker_Example' do
  pod 'RRCountryCodePicker', :path => '../'

  target 'RRCountryCodePicker_Tests' do
    inherit! :search_paths

    
  end
end
